### ISSUE TITLE
Phrase verbesserungen

### ISSUE THREAD

**Issue by simple4dev** [PassCody/Trinity-Core#1]
Metatabellen nötig
Einige Dateien sind nicht mit Metatabellen versehen.

Trinity-Core/Repack/Teachers/WaffenLehrer.lua
Trinity-Core/Repack/Teleporter/MallPorter.lua
Trinity-Core/Repack/Teleporter/StrangePorter.lua

Diese sollten einmal überschrieben werden.
Gruß. Top Repo!

**Comment by PassCody** [comment]
Trinity-Core/Repack/Teachers/WaffenLehrer.lua ist fertig.

Die Teleporter werden so gelassen weil es so oder so auf das selbe hinaus kommen würde.

**Comment by PassCody** [comment]
Ich habe gerade noch mal alle Script durch gesehen und über all wo die Metatabellen gefehlt haben diese eingebunden und den Row for Row Code dezimiert.

Viel spaß mit dem repo.

Grüße ;)
